### ISSUE TITLE
Noto Sans Kannada and Noto Serif Kannada: ZWJ not working as expected after {U+0CB0, U+0CCD}

### ISSUE THREAD

**Issue by MayuraVerma** [notofonts/kannada#1]
I am not sure if this is Noto Sans Kannada defect in Chrome on Mac or if this is Chrome issue or harfbuzz issue.

There seems to be an issue with "ZERO WIDTH JOINER" and "\u0cb0\u0ccd" combination.
\u0cb0\u0ccd\u200d\u0c95

incorrect display in chrome
![incorrect display in chrome](https://cloud.githubusercontent.com/assets/14062593/19226292/ecd28c60-8e6e-11e6-8b5b-ed480a80a0a5.png)

correct display in ms word
![correct display in ms word](https://cloud.githubusercontent.com/assets/14062593/19226287/d350a7fe-8e6e-11e6-8a71-9706efa24a57.png)

Check the below text in chrome and comparing it with Microsoft word.

ರ್‍ಕ ರ್‍ಖ ರ್‍ಗ ರ್‍ಘ ರ್‍ಙ ರ್‍ಚ ರ್‍ಛ ರ್‍ಜ ರ್‍ಝ ರ್‍ಞ ರ್‍ಟ ರ್‍ಠ ರ್‍ಡ ರ್‍ಢ ರ್‍ಣ ರ್‍ತ ರ್‍ಥ ರ್‍ದ ರ್‍ಧ ರ್‍ನ ರ್‍ಪ ರ್‍ಫ ರ್‍ಬ ರ್‍ಭ ರ್‍ಮ ರ್‍ಯ ರ್‍ರ ರ್‍ಱ ರ್‍ಲ ರ್‍ವ ರ್‍ಶ ರ್‍ಷ ರ್‍ಸ ರ್‍ಹ ರ್‍ಳ ರ್‍ೞ

Weblink to see the issue live: https://en.wikipedia.org/wiki/Kannada_alphabet

**Comment by SKing-2003** [comment]
This seems to be fixed on the latest versions of harfbuzz.

**Comment by MayuraVerma** [comment]
Thank you. This is not a font issue. 
Thanks for closing issue.
