### ISSUE TITLE
Move anchor in 25CC greatly down in Serif

### ISSUE THREAD

**Issue by Mercury13** [notofonts/kannada#12]
### Title 
Candrabindu in 25CC is too high → move anchor in 25CC
It’s probably safe: it’s used for 0C81 and a few Vedic umlauts, and they all are far from anchor.

### Font 
NotoSerifKannada-Regular.ttf

### Where the font came from, and when
Site: your release repo
Date: 2022-07-10

### Font Version
2.003

### OS name and version
All OS

### Application name and version
All apps

### Issue
  1. Write 25CC+0C81
  2. Candrabindu should be at least in line
  3. Candrabindu is too high

### Character data
25CC Dotted circle
0C81 Kannada sign Candrabindu

### Screenshot
![image](https://user-images.githubusercontent.com/10164882/178125144-634dbc93-5e53-4eb1-8f1c-d1c014c1d5ed.png)

**Comment by sridatta1** [comment]
Also needs to be verified in Noto Sans Kannada.
The implementation in Tiro Kannada and the related discussion here can be looked into 
https://github.com/TiroTypeworks/Indigo/issues/20#issuecomment-1166568022

**Comment by Mercury13** [comment]
Interesting. I considered taking Tiro into my project instead of Noto. Noto’s coverage of Devanagari is so wide that no one can repeat, and I found a cheap way to close Noto’s bugs. Telugu — I just didn’t check. Kannada — who knows; maybe I’ll wait until they implement a new U15 character. Gurmukhi is so simple that no matter what to take. Tamil — system fonts are enough by now.
