### ISSUE TITLE
review of Serif Kannada change proposal

### ISSUE THREAD

**Issue by marekjez86** [notofonts/kannada#2]
@MayuraVerma : this is related to Kannada font. could you help by reviewing the suggested changes to the Serif Kannada font documented in the enclosed PDF? Please post comments here. 

Anybody else who knows something about Kannada: feel free also comment on these changes.

Thank you for any help you might be able to offer.

**Comment by sridatta1** [comment]
Can this is issue be closed as it more generic and mostly resolved? separate issues can raised by me or others for the specific issues

**Comment by simoncozens** [comment]
Sure, thank you!
