### ISSUE TITLE
Noto Serif Kannada Defect with Double below form consonants, U+0CC3 U+0CC4 U+0CC8

### ISSUE THREAD

**Issue by chandrab699** [notofonts/kannada#4]
### Title 
  > Noto Serif Kannada Defect with Double below form consonants and below form vowels U+0CC3 U+0CC4 U+0CC8

### Font 
  > 'NotoSansKannada-Regular.ttf'.

### Where the font came from, and when
  >  https://github.com/googlei18n/noto-fonts/tree/master/phaseIII_only/hinted/ttf/NotoSerifKannada
  >   Date: 2018-09-14 

### Font Version
  > 2.001

### OS name and version
  > Windows 7 SP1

### Application name and version
  > MS Word 2016, version 16.0.6965.2117

### Issue
  > Noto Serif Kannada font is overlapping the below form  double/triple consonants and below form vowels U+0CC3 U+0CC4 U+0CC8

### Character data
  > 

ಕ್ಕ್ಖ | ಕ್ಖ್ಕ | ಕ್ಗ್ಕ | ಕ್ಘ್ಕ | ಕ್ಙ್ಕ | ಕ್ಚ್ಕ | ಕ್ಛ್ಕ | ಕ್ಜ್ಕ | ಕ್ಝ್ಕ | ಕ್ಞ್ಕ | ಕ್ಟ್ಕ | ಕ್ಠ್ಕ | ಕ್ಡ್ಕ | ಕ್ಢ್ಕ | ಕ್ಣ್ಕ | ಕ್ತ್ಕ | ಕ್ಥ್ಕ | ಕ್ದ್ಕ | ಕ್ಧ್ಕ | ಕ್ನ್ಕ | ಕ್ಪ್ಕ | ಕ್ಫ್ಕ | ಕ್ಬ್ಕ | ಕ್ಭ್ಕ | ಕ್ಮ್ಕ | ಕ್ಯ್ಕ | ಕ್ರ್ಕ | ಕ್ಱ್ಕ | ಕ್ಲ್ಕ | ಕ್ವ್ಕ | ಕ್ಶ್ಕ | ಕ್ಷ್ಕ | ಕ್ಸ್ಕ | ಕ್ಹ್ಕ | ಕ್ಳ್ಕ | ಕ್ೞ್ಕ
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
ಕ್ಕೃ | ಕ್ಖೃ | ಕ್ಗೃ | ಕ್ಘೃ | ಕ್ಙೃ | ಕ್ಚೃ | ಕ್ಛೃ | ಕ್ಜೃ | ಕ್ಝೃ | ಕ್ಞೃ | ಕ್ಟೃ | ಕ್ಠೃ | ಕ್ಡೃ | ಕ್ಢೃ | ಕ್ಣೃ | ಕ್ತೃ | ಕ್ಥೃ | ಕ್ದೃ | ಕ್ಧೃ | ಕ್ನೃ | ಕ್ಪೃ | ಕ್ಫೃ | ಕ್ಬೃ | ಕ್ಭೃ | ಕ್ಮೃ | ಕ್ಯೃ | ಕ್ರೃ | ಕ್ಱೃ | ಕ್ಲೃ | ಕ್ವೃ | ಕ್ಶೃ | ಕ್ಷೃ | ಕ್ಸೃ | ಕ್ಹೃ | ಕ್ಳೃ | ಕ್ೞೃ
ಕ್ಕೄ | ಕ್ಖೄ | ಕ್ಗೄ | ಕ್ಘೄ | ಕ್ಙೄ | ಕ್ಚೄ | ಕ್ಛೄ | ಕ್ಜೄ | ಕ್ಝೄ | ಕ್ಞೄ | ಕ್ಟೄ | ಕ್ಠೄ | ಕ್ಡೄ | ಕ್ಢೄ | ಕ್ಣೄ | ಕ್ತೄ | ಕ್ಥೄ | ಕ್ದೄ | ಕ್ಧೄ | ಕ್ನೄ | ಕ್ಪೄ | ಕ್ಫೄ | ಕ್ಬೄ | ಕ್ಭೄ | ಕ್ಮೄ | ಕ್ಯೄ | ಕ್ರೄ | ಕ್ಱೄ | ಕ್ಲೄ | ಕ್ವೄ | ಕ್ಶೄ | ಕ್ಷೄ | ಕ್ಸೄ | ಕ್ಹೄ | ಕ್ಳೄ | ಕ್ೞೄ
ಕ್ಕ್ಖೃ | ಕ್ಖ್ಕೃ | ಕ್ಗ್ಕೃ | ಕ್ಘ್ಕೃ | ಕ್ಙ್ಕೃ | ಕ್ಚ್ಕೃ | ಕ್ಛ್ಕೃ | ಕ್ಜ್ಕೃ | ಕ್ಝ್ಕೃ | ಕ್ಞ್ಕೃ | ಕ್ಟ್ಕೃ | ಕ್ಠ್ಕೃ | ಕ್ಡ್ಕೃ | ಕ್ಢ್ಕೃ | ಕ್ಣ್ಕೃ | ಕ್ತ್ಕೃ | ಕ್ಥ್ಕೃ | ಕ್ದ್ಕೃ | ಕ್ಧ್ಕೃ | ಕ್ನ್ಕೃ | ಕ್ಪ್ಕೃ | ಕ್ಫ್ಕೃ | ಕ್ಬ್ಕೃ | ಕ್ಭ್ಕೃ | ಕ್ಮ್ಕೃ | ಕ್ಯ್ಕೃ | ಕ್ರ್ಕೃ | ಕ್ಱ್ಕೃ | ಕ್ಲ್ಕೃ | ಕ್ವ್ಕೃ | ಕ್ಶ್ಕೃ | ಕ್ಷ್ಕೃ | ಕ್ಸ್ಕೃ | ಕ್ಹ್ಕೃ | ಕ್ಳ್ಕೃ | ಕ್ೞ್ಕೃ
ಕ್ಕ್ಖೄ | ಕ್ಖ್ಕೄ | ಕ್ಗ್ಕೄ | ಕ್ಘ್ಕೄ | ಕ್ಙ್ಕೄ | ಕ್ಚ್ಕೄ | ಕ್ಛ್ಕೄ | ಕ್ಜ್ಕೄ | ಕ್ಝ್ಕೄ | ಕ್ಞ್ಕೄ | ಕ್ಟ್ಕೄ | ಕ್ಠ್ಕೄ | ಕ್ಡ್ಕೄ | ಕ್ಢ್ಕೄ | ಕ್ಣ್ಕೄ | ಕ್ತ್ಕೄ | ಕ್ಥ್ಕೄ | ಕ್ದ್ಕೄ | ಕ್ಧ್ಕೄ | ಕ್ನ್ಕೄ | ಕ್ಪ್ಕೄ | ಕ್ಫ್ಕೄ | ಕ್ಬ್ಕೄ | ಕ್ಭ್ಕೄ | ಕ್ಮ್ಕೄ | ಕ್ಯ್ಕೄ | ಕ್ರ್ಕೄ | ಕ್ಱ್ಕೄ | ಕ್ಲ್ಕೄ | ಕ್ವ್ಕೄ | ಕ್ಶ್ಕೄ | ಕ್ಷ್ಕೄ | ಕ್ಸ್ಕೄ | ಕ್ಹ್ಕೄ | ಕ್ಳ್ಕೄ | ಕ್ೞ್ಕೄ
ಕ್ಕೈ | ಕ್ಖೈ | ಕ್ಗೈ | ಕ್ಘೈ | ಕ್ಙೈ | ಕ್ಚೈ | ಕ್ಛೈ | ಕ್ಜೈ | ಕ್ಝೈ | ಕ್ಞೈ | ಕ್ಟೈ | ಕ್ಠೈ | ಕ್ಡೈ | ಕ್ಢೈ | ಕ್ಣೈ | ಕ್ತೈ | ಕ್ಥೈ | ಕ್ದೈ | ಕ್ಧೈ | ಕ್ನೈ | ಕ್ಪೈ | ಕ್ಫೈ | ಕ್ಬೈ | ಕ್ಭೈ | ಕ್ಮೈ | ಕ್ಯೈ | ಕ್ರೈ | ಕ್ಱೈ | ಕ್ಲೈ | ಕ್ವೈ | ಕ್ಶೈ | ಕ್ಷೈ | ಕ್ಸೈ | ಕ್ಹೈ | ಕ್ಳೈ | ಕ್ೞೈ
ಕ್ಕ್ಖೈ | ಕ್ಖ್ಕೈ | ಕ್ಗ್ಕೈ | ಕ್ಘ್ಕೈ | ಕ್ಙ್ಕೈ | ಕ್ಚ್ಕೈ | ಕ್ಛ್ಕೈ | ಕ್ಜ್ಕೈ | ಕ್ಝ್ಕೈ | ಕ್ಞ್ಕೈ | ಕ್ಟ್ಕೈ | ಕ್ಠ್ಕೈ | ಕ್ಡ್ಕೈ | ಕ್ಢ್ಕೈ | ಕ್ಣ್ಕೈ | ಕ್ತ್ಕೈ | ಕ್ಥ್ಕೈ | ಕ್ದ್ಕೈ | ಕ್ಧ್ಕೈ | ಕ್ನ್ಕೈ | ಕ್ಪ್ಕೈ | ಕ್ಫ್ಕೈ | ಕ್ಬ್ಕೈ | ಕ್ಭ್ಕೈ | ಕ್ಮ್ಕೈ | ಕ್ಯ್ಕೈ | ಕ್ರ್ಕೈ | ಕ್ಱ್ಕೈ | ಕ್ಲ್ಕೈ | ಕ್ವ್ಕೈ | ಕ್ಶ್ಕೈ | ಕ್ಷ್ಕೈ | ಕ್ಸ್ಕೈ | ಕ್ಹ್ಕೈ | ಕ್ಳ್ಕೈ | ಕ್ೞ್ಕೈ

### Screenshot
Noto Serif Kannada
![image](https://user-images.githubusercontent.com/30884806/45563364-baefcd00-b812-11e8-96a6-47d6ae0788ab.png)

Noto Sans Kannada
![image](https://user-images.githubusercontent.com/30884806/45563454-0013ff00-b813-11e8-9b1e-2ba321a4bd86.png)

**Comment by simoncozens** [comment]
I just ran a collision test; all of these are passing.
