### ISSUE TITLE
AppleCoreText Issue with Kannada text

### ISSUE THREAD

**Issue by MayuraVerma** [notofonts/kannada#5]
## Defect Report
This is not an issue with Noto Sans Kannada Font, but this is an issue with iOS and MacOS, "AppleCoreText API". If you can please report it to Apple, It might traction with Apple Engineers.

### Title 
  > Kannada text is broken in Notes app in iOS and mac OS

### Font 
  > 'NotoSansKannada-Regular.ttf'

### Where the font came from, and when
  > part of iOS 13 and mac OS Catalina

### OS name and version
  > iOS 13.2.2 (17B102)
  > mac OS catalina 10.15.1 (19B88)

### Application name and version
  > Notes app

### Issue
  > These text is displayed correctly in "NSTextView" field, but breaks in "NSTextField" text field.
Notes app and all forms with text editing uses "NSTextField".
Open Notes app in iOS or mac OS, type the below text.
ಕಜ್ನೋ
ಕಜ್ನ್ಕೋ
ಕಜ್ನ್ಕ್ರೋ
ಕಜ಼್ನೋ
ಕಜ಼್ನ್ಕೋ
ಕಜ್ಫ಼ೋ
ಕಜ್ನ್ಫ಼ೋ
ಕಜ್ಜ಼್ಫ಼ೋ
ಕಜ಼್ಜ಼್ಫ಼ೋ

Noto Sans Kannada font is breaking in iOS and mac OS with cluster of Kannada text 
<any Kannada Consonant> U+0CCD <any Kannada Consonant> U+0CCD <any Kannada Consonant> U+0CCA 
<any Kannada Consonant> U+0CCD <any Kannada Consonant> U+0CCD <any Kannada Consonant> U+0CCB
<any Kannada Consonant> U+0CBC U+0CCD <any Kannada Consonant> U+0CBC U+0CCD <any Kannada Consonant> U+0CBC U+0CCA 
<any Kannada Consonant> U+0CBC U+0CCD <any Kannada Consonant> U+0CBC U+0CCD <any Kannada Consonant> U+0CBC U+0CCB

### Screenshot
  > Actual text in Notes App while editing. "NSTextField"
![BrokenText](https://user-images.githubusercontent.com/14062593/68793043-1e8daa00-0612-11ea-81fd-dc0635406ccf.png)

  > Expected text in email while reading. "NSTextView"
![ExpectedTextEmailApp](https://user-images.githubusercontent.com/14062593/68793034-19c8f600-0612-11ea-82da-bfe7334dd1fb.jpg)

**Comment by MayuraVerma** [comment]
**Noto Sans Kannada is the system UI font in iOS and mac OS.**

### **SOLUTION:**
This issue can be resolved in font with precomposed for Kannada consonant and U+0CCA glyph in the font. This would reduced the glyph count by 2, similar to **Tiro Kannada** at https://github.com/TiroTypeworks/Indigo/tree/main/fonts/TiroKannada by @TiroTypeworks 

Glyph count in Noto Sans Kannada:
**Kannada consonant and U+0CCB** is broken down to Kannada consonant base + U+0CC6 + U+0CC2 + U+0CD5 : **Glyph count 4**
**Kannada consonant and U+0CCA** is broken down to Kannada consonant base + U+0CC6 + U+0CC2: **Glyph count 3**

Tiro Kannada:
**Kannada consonant and U+0CCB** is broken down to (Precomposed: Kannada consonant base + U+0CC6 + U+0CC2) + U+0CD5 : **Glyph count 2**
**Kannada consonant and U+0CCA** is broken down to (Precomposed: Kannada consonant base + U+0CC6 + U+0CC2): **Glyph count 1**

Tiro Kannada font do not exhibit is this issue in iOS/macOS, because of its 2 less glyph to deal for TextKit.

Both Noto Sans Kannada and Noto Serif Kannada overcome the glyph count limitation in iOS and macOS.

**Background:**

Glyph count limitation in TextKit (ver 1) can be found in below two videos.

WWDC 2021, watch from 7:00
https://developer.apple.com/videos/play/wwdc2021/10061
WWDC 2022, watch from 15:20
https://developer.apple.com/videos/play/wwdc2022/10090

TextKit2 was first introduced in 2020. 

iOS 16/mac OS ventura which is slated to be released in Sep2022. TextKit2 is made default only in **UITextView/NSTextView** but developers can opt out, if they have compatibility issue. Still no word on when Texkit2 will be default and made in **UITextField/NSTextField**, **UILabel/NSComboNox**.

UITextField/NSTextField is the most used field in iOS/macOS for text entry, editing and viewing for paragraphs.

Speed at which, Apple is implementing TextKit2 and providing backwards compatibility to TextKit. It might take another **5-10 years**, by the time, TextKit2 becomes default and mandatory text engine across all text fields in iOS and macOS.

I request Noto Fonts to please implement this solution at the earliest.

**Comment by MayuraVerma** [comment]
@marekjez86 @nizarsq Please review this and prioritize.
Noto Sans Kannada is the system UI font in iOS and mac OS.
Solution proposed above will resolve a long standing and annoying bug in Kannada font in iOS and macOS

**Comment by MayuraVerma** [comment]
Noto Sans Kannada vs Tiro Kannada in Mac OS Ventura
<img width="494" alt="Screen Shot 2022-06-22 at 1 39 22 PM" src="https://user-images.githubusercontent.com/14062593/175112503-d0e9ba77-bef5-4adf-98d0-eb65b47e218e.png">

**Comment by simoncozens** [comment]
Thanks for this; there seem to be various messes here. I see in the Indigo bug there is the suggestion of attaching the candrabindu via mark positioning. I will work on this, but I have quite a bit of other things to go through first.

**Comment by MayuraVerma** [comment]
iOS17 beta 1 resolves this issue. Please check and close.

**Comment by omshivaprakash** [comment]
Yes, it’s a big relief. ![image](https://github.com/notofonts/kannada/assets/115216/e42bad1e-c93b-4baf-a815-627e801a7506)

**Comment by simoncozens** [comment]
Finally. Thanks, Apple!
