### ISSUE TITLE
Please move anchor 3 on 25СС to the centre

### ISSUE THREAD

**Issue by Mercury13** [notofonts/kannada#58]
### Title 
Upper umlauts (e.g. candrabindu) are well above line

### Font 
NotoSerifKannada-Regular.ttf

### Where the font came from, and when
Site: this repo, beta branch
Date: 2023-07-11

### Font Version
2.004

### OS name and version
All OS

### Application name and version
All apps

### Issue
Upper umlauts (e.g. candrabindu) are well above line. AFAIU, they are so rare that there’s no point to make line taller → at least move inside the line on 25CC.

Alternate (harder) solution: 1. Move those anchors to actual bottom of umlauts. 2. Check manually on every glyph where it’s safe to hang those umlauts. Does it make sense? Kannada differs from other Indic scripts, it has very few upper umlauts.

### Character data
U+0C81 Kannada sign Candrabindu
U+1CD0 Vedic tone Karshana
U+1CD2 Vedic tone Prenkha
U+1CDA Vedic tone Double svarita
U+1CF4 Vedic tone Candra above
U+25CC dotted circle

### Screenshot
![изображение](https://github.com/notofonts/kannada/assets/10164882/c489a529-877e-472b-aa51-056ff29ab79b)
![изображение](https://github.com/notofonts/kannada/assets/10164882/533942e0-1469-44aa-90be-9806f2454aba)

**Comment by simoncozens** [comment]
As you show in your first screenshot, the current behaviour shows correctly how the mark is positioned in this font. So there is no bug here.
