### ISSUE TITLE
Bug in Noto Sans Kannada UI family shaping of `ಫ್ಟ್ `

### ISSUE THREAD

**Issue by chrissimpkins** [notofonts/kannada#60]
This issue was reported by localization testers in the Android environment and appears to be in the Noto Sans Kannada **UI** family.  It is not present in the default non-UI design.

 ‎0CAB KANNADA LETTER PHA
 ‎0CCD KANNADA SIGN VIRAMA
 ‎0C9F KANNADA LETTER TTA
 ‎0CCD KANNADA SIGN VIRAMA

The following image was generated in Font Goggles with [the v2.005 UI and non-UI / default Kannada release fonts](https://github.com/notofonts/kannada/releases/tag/NotoSansKannada-v2.005).

![3ryCvyJWHARovGN](https://github.com/user-attachments/assets/8b8d7552-8b4d-494f-8ed5-5dd7461e9ba9)

---

b/331750009

**Comment by simoncozens** [comment]
Fixed in 5f7cef7.
