### ISSUE TITLE
Subscript of ಕ್ಷ needs to be corrected in Noto Sans Kannada

### ISSUE THREAD

**Issue by sridatta1** [notofonts/kannada#9]
### Title 
Subscript of ಕ್ಷ needs to be corrected in Noto Sans Kannada, to be matched as in Serif Kannada
### Font 
NotoSansKannada-Regular.ttf

### Where the font came from, and when
  > For example:
  >   Site: https://fonts.google.com/download?family=Noto%20Sans%20Kannada
  >   Date: 2022 June 4

### Font Version
2.001

### OS name and version
Ubuntu 18.04

### Issue
for ಕ್ಷ  kṣa when it is a subscript, ಷ subscript needs to be below ಕ subscript.

  1. Steps to reproduce
  test ತ್ಕ್ಷ tkṣa
  2. Observed results
  
![image](https://user-images.githubusercontent.com/23263723/171996930-72eb1ca8-bf4b-4283-a6f0-c80fbeac31a2.png)

  3. Expected results
  
![image](https://user-images.githubusercontent.com/23263723/171996946-1c96aaed-3bfb-430d-a993-36b465dbcf7f.png)

  7. Additional information 
Works properly in Noto Serif Kannada

### Character data

ತ್ಕ್ಷ

**Comment by simoncozens** [comment]
Somehow this is looking even worse now.
